// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOWzeCgeEVRrLGJM0Cp0W-gQeJsY6QDg',
    appId: '1:686958564481:web:8f3e704cf84f84a8fee980',
    messagingSenderId: '686958564481',
    projectId: 'dima-58cb8',
    authDomain: 'dima-58cb8.firebaseapp.com',
    databaseURL: 'https://dima-58cb8-default-rtdb.firebaseio.com',
    storageBucket: 'dima-58cb8.appspot.com',
    measurementId: 'G-YCRGB6X93D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmv4n8pvqrm-gmuPIMe8BYY6grdMEc5pQ',
    appId: '1:686958564481:android:dd8717ba8494dd5afee980',
    messagingSenderId: '686958564481',
    projectId: 'dima-58cb8',
    databaseURL: 'https://dima-58cb8-default-rtdb.firebaseio.com',
    storageBucket: 'dima-58cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCebtI4tNyvgq4TbYDQNjOVzXkMUvz-LJs',
    appId: '1:686958564481:ios:ca4ae3f2f276eb4dfee980',
    messagingSenderId: '686958564481',
    projectId: 'dima-58cb8',
    databaseURL: 'https://dima-58cb8-default-rtdb.firebaseio.com',
    storageBucket: 'dima-58cb8.appspot.com',
    iosBundleId: 'com.polimi.dimaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCebtI4tNyvgq4TbYDQNjOVzXkMUvz-LJs',
    appId: '1:686958564481:ios:47e4747c86203573fee980',
    messagingSenderId: '686958564481',
    projectId: 'dima-58cb8',
    databaseURL: 'https://dima-58cb8-default-rtdb.firebaseio.com',
    storageBucket: 'dima-58cb8.appspot.com',
    iosBundleId: 'com.polimi.dimaProject.RunnerTests',
  );
}
