// Mocks generated by Mockito 5.4.4 from annotations
// in dima_project/test/mocks/mock_notification_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dima_project/models/message.dart' as _i10;
import 'package:dima_project/models/private_chat.dart' as _i9;
import 'package:dima_project/services/database_service.dart' as _i3;
import 'package:dima_project/services/notification_service.dart' as _i4;
import 'package:firebase_messaging/firebase_messaging.dart' as _i2;
import 'package:flutter/cupertino.dart' as _i6;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseMessaging_0 extends _i1.SmartFake
    implements _i2.FirebaseMessaging {
  _FakeFirebaseMessaging_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseService_1 extends _i1.SmartFake
    implements _i3.DatabaseService {
  _FakeDatabaseService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i4.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseMessaging get messaging => (super.noSuchMethod(
        Invocation.getter(#messaging),
        returnValue: _FakeFirebaseMessaging_0(
          this,
          Invocation.getter(#messaging),
        ),
      ) as _i2.FirebaseMessaging);

  @override
  set messaging(_i2.FirebaseMessaging? _messaging) => super.noSuchMethod(
        Invocation.setter(
          #messaging,
          _messaging,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DatabaseService get databaseService => (super.noSuchMethod(
        Invocation.getter(#databaseService),
        returnValue: _FakeDatabaseService_1(
          this,
          Invocation.getter(#databaseService),
        ),
      ) as _i3.DatabaseService);

  @override
  set databaseService(_i3.DatabaseService? _databaseService) =>
      super.noSuchMethod(
        Invocation.setter(
          #databaseService,
          _databaseService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> requestNotificationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestNotificationPermission,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void initLocalNotifications(
    _i6.BuildContext? context,
    _i2.RemoteMessage? message,
    Function? changeIndex,
    Function? clearNavigatorKeys,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #initLocalNotifications,
          [
            context,
            message,
            changeIndex,
            clearNavigatorKeys,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void firebaseInit(
    _i6.BuildContext? context,
    Function? changeIndex,
    Function? clearNavigatorKeys,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #firebaseInit,
          [
            context,
            changeIndex,
            clearNavigatorKeys,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String> getDeviceToken() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceToken,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDeviceToken,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setupToken(_i8.WidgetRef? ref) => (super.noSuchMethod(
        Invocation.method(
          #setupToken,
          [ref],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setUpInteractMessage(
    _i6.BuildContext? context,
    Function? changeIndex,
    Function? clearNavigatorKeys,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUpInteractMessage,
          [
            context,
            changeIndex,
            clearNavigatorKeys,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> handleMessage(
    _i6.BuildContext? context,
    _i2.RemoteMessage? message,
    Function? changeIndex,
    Function? clearNavigatorKeys,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleMessage,
          [
            context,
            message,
            changeIndex,
            clearNavigatorKeys,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> forgroundMessage() => (super.noSuchMethod(
        Invocation.method(
          #forgroundMessage,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<String> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAccessToken,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> sendPrivateChatNotification(
    _i9.PrivateChat? privateChat,
    _i10.Message? chatMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotificationOnPrivateChat,
          [
            privateChat,
            chatMessage,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendGroupNotification(
    String? groupId,
    _i10.Message? chatMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotificationOnGroup,
          [
            groupId,
            chatMessage,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendEventNotification(
    String? eventName,
    String? eventId,
    bool? detail,
    String? detailId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEventNotification,
          [
            eventName,
            eventId,
            detail,
            detailId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToTopics() => (super.noSuchMethod(
        Invocation.method(
          #subscribeToTopics,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTopicSubscriptions(List<String>? newCategories) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTopicSubscriptions,
          [newCategories],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeAndClearTopics() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeAndClearTopics,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initialize(
    _i6.BuildContext? context,
    _i8.WidgetRef? ref,
    Function? changeIndex,
    Function? clearNavigatorKeys,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            context,
            ref,
            changeIndex,
            clearNavigatorKeys,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
